services:
  app:
    build: .
    container_name: locomotive-ai
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./cache:/app/cache
      - ./chroma_db:/app/chroma_db

  nginx:
    image: nginx:alpine
    container_name: locomotive-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
